#! /usr/bin/env sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
CONFIG_HANDLER=$DIR"/digital-nomad-bin/config-handler.rb"

case "$1" in
	grep)
		read NOTES_DIR PUBLIC_DIR BOX_DIR <<<$(ruby $CONFIG_HANDLER "notes-public-box-dir")
		[[ ! -z $NOTES_DIR ]] && cd $NOTES_DIR && grep -nriI --color "$2" *
		[[ ! -z $NOTES_DIR ]] && cd - &> /dev/null
		[[ ! -z $PUBLIC_DIR ]] && cd $PUBLIC_DIR && find . -name "*.md" | xargs grep -nriI --color "$2"
		[[ ! -z $PUBLIC_DIR ]] && cd - &> /dev/null
		[[ ! -z $BOX_DIR ]] && cd "$BOX_DIR" && find . -name "*.md" | xargs grep -nriI --color "$2"
		[[ ! -z $BOX_DIR ]] && cd - &> /dev/null
		;;
    grep_todo)
		ICS_DIR=$(ruby $CONFIG_HANDLER "log-ics-dir")
		grep -nriI --color=always --include \*.ics "$2" $ICS_DIR
        ;;
	grep_cgi)
		read NOTES_DIR PUBLIC_DIR BOX_DIR <<<$(ruby $CONFIG_HANDLER "notes-public-box-dir")
		[[ ! -z $NOTES_DIR ]] && grep -nriI --color=always --exclude-dir="\.*" --include \*.md --include \*.txt "$2" $NOTES_DIR
		[[ ! -z $PUBLIC_DIR ]] && grep -nriI --color=always --exclude-dir="\.*" --include \*.md --include \*.txt "$2" $PUBLIC_DIR
		[[ ! -z $BOX_DIR ]] && grep -nriI --color=always --exclude-dir="\.*" --include \*.md --include \*.txt "$2" "$BOX_DIR"
		;;
	blog-open-last)
		BLOG_DIR=$(ruby $CONFIG_HANDLER "blog-dir")
		cd $BLOG_DIR && ls | grep md | tail -1 | xargs open
		cd - &> /dev/null
		;;
	blog-md-tips)
		echo "<div align=\"center\"><img src=\"_img/your-img.png\"/></div>"
		echo "<a name=\"anchor-id\"></a>"
		;;
	blog-update)
		CMD=$(ruby $CONFIG_HANDLER "blog-metadata")
        ruby $CMD
		;;
	blog) 
		if [ -z "$2" ]
		then
			echo "dn blog title"
			exit 1
		fi
		BLOG_DIR=$(ruby $CONFIG_HANDLER "blog-dir")
		cd $BLOG_DIR && touch "`date +"%Y%m%d%H%M"`-$2.md"
        echo -e "$2\n====\n\nTag\n====\n," > "`date +"%Y%m%d%H%M"`-$2.md"
		cd - &> /dev/null
		echo $BLOG_DIR/`date +"%Y%m%d%H%M"`-$2.md
		;;
	log-rotator)	
		if [ -z "$2" ] || [ -z "$3" ]
		then
			echo "log rotator needs 'log-type(work, search, seed and bash)' and 'machine(mac, ..)"
			exit 1
		fi
		CMD=$(ruby $CONFIG_HANDLER "log-rotator")
        ruby $CMD "$2" "$3"
		;;
	*)
		echo "dn grep/grep_cgi/grep_todo keyword"
		echo "dn blog title"
		echo "dn blog-open-last"
		echo "dn blog-md-tips"
		echo "dn blog-update"
		echo "dn log-rotator"
		;;
esac
