#! /usr/bin/env sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
CONFIG_LOADER=$DIR"/common/config-loader.rb"

case "$1" in
	grep)
		cd ~/notes && grep -nriI --color "$2" *
		cd - &> /dev/null
		cd ~/Dropbox/Public && find . -name "*.md" | xargs grep -nriI --color "$2"
		cd - &> /dev/null
		cd ~/Box\ Sync/workingDocs/working && find . -name "*.md" | xargs grep -nriI --color "$2"
		cd - &> /dev/null
        #ruby ~/workspace/fyac/actions/action.rb "$2" " _[result_dngrep]_"
		#grep -nriI --color=always "$2" ~/notes/*
		;;
    grep_todo)
		grep -nriI --color=always --include \*.ics "$2" ~/Dropbox/Log
        #ruby ~/workspace/fyac/actions/action.rb "$2" " _[result_dntodo]_"
        ;;
	grep_cgi)
		grep -nriI --color=always --include \*.md --include \*.txt "$2" ~/Dropbox/Notes
		grep -nriI --color=always --include \*.md --include \*.txt "$2" ~/Dropbox/Public
		grep -nriI --color=always --include \*.md --include \*.txt "$2" "~/Box Sync/작업문서/작업중"
		;;
	blog-open-last)
		BLOG_DIR=(`ruby ${CONFIG_LOADER} "blog-dir"`)
		cd $BLOG_DIR && ls | grep md | tail -1 | xargs open
		cd - &> /dev/null
		;;
	blog-update)
		CMD=(`ruby ${CONFIG_LOADER} "blog-metadata"`)
        ruby $CMD
		;;
	project-update)
		CMD=(`ruby ${CONFIG_LOADER} "project-metadata"`)
        ruby $CMD
		;;
	blog) 
		if [ -z "$2" ]
		then
			echo "dn blog title"
			exit 1
		fi
		BLOG_DIR=(`ruby ${CONFIG_LOADER} "blog-dir"`)
		cd $BLOG_DIR && touch "`date +"%Y%m%d%H%M"`-$2.md"
        echo -e "$2\n====\n\nTag\n====\n," > "`date +"%Y%m%d%H%M"`-$2.md"
		cd - &> /dev/null
		echo $BLOG_DIR/`date +"%Y%m%d%H%M"`-$2.md
		;;
	*)
		echo "dn grep/grep_cgi/grep_todo keyword"
		echo "dn blog title"
		echo "dn blog-open-last"
		echo "dn blog-update"
		echo "dn project-update"
		;;
esac
