# http://docs.ansible.com/ansible/YAMLSyntax.html

# computer name.
# eg. mac, t1125m, xd8, ...
computer_name: 'mac'

# paths for log-me
paths:
  git : '/usr/bin/git'

  log_file : '~/workspace/worklog.log'
  log_dir : '~/Dropbox/Log'

  notes_dir : '~/Dropbox/Notes'
  notes_dir_alias : '~/notes'
  box_working_dir : '~/Box Sync/Documents/working'
  box_working_dir_alias : '~/notes-working-docs'
  blog_dir : '~/workspace/mdblog/blog'

server:
  port_config : 'fyac/extern-apps/chrome-menu-result/manifest.json'
  search_log_file : '~/workspace/search.log'
  seeds_log_file : '~/workspace/seeds.log'
  use_on_nas : false

file_tagger:
  cloud_dir : '~/Dropbox/Log/file-tagger'
  nas_dir : '/nas/dir/here'
