# http://docs.ansible.com/ansible/YAMLSyntax.html

# computer name.
# eg. mac, t1125m, xd8, ...
computer_name: 'mac'

# paths for log-me
paths:
  git : '/usr/bin/git'

  # for dropbox
  notes_dir : '~/Dropbox/Notes'
  log_dir : '~/Dropbox/Log'
  blog_dir : '~/Dropbox/public/blog'

  # for box
  box_working_dir : '~/Box Sync/workingDocs/working'
  
  # log
  log_file : '~/workspace/worklog.log'

server:
  port_config : 'fyac/apps/chrome-menu-result/manifest.json'
  search_log_file : '~/workspace/search.log'
