# http://docs.ansible.com/ansible/YAMLSyntax.html

#tagger-id-result.yml
#total : 24039
#  item_per_page : 24039 (or 300, calculation prefix- 001 or 0001)
#  uniq_files : 24000
#  expected_duplications : 39
#     - candidate : 'xxx/xxx/xxx, yyy/yyy/yyy'
#     - candidate : ...   

#id : hash-code
# - file_name : (진짜파일이름, 사진/그밑.. 이렇게 나타냄) (merging eg : dropbox_2015_file_name.jpg)
# - tags : 'dropbox, 2015'
# - date :
# - location : 

file_tagger_config:
  tagger_id : 'photo-manager'
  src:
    root_path : '/your/src/dir/for/tagging'
    use_multiple_result : true
    multiple_result_type : 'directory' # or paging
    paging_item_count : 300
    hash_limit : '100MB'
    #use_date, use_location
    filter:
      - exclude_tag_2015 # path 2015 is exclude from tag
      - include_tag_메인_액자 # path
      - merge_tag_dropbox # path dropbox is added in merging
  target:
    root_path : '/optional/dir/for/merging'
    use_merging : false # if it is false, target is just ignored
    filter:
      - add_prefix_dropbox
      - add_suffix_2015
